import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import { ThemeProvider } from "next-themes";
import Footer from "@/Components/Footer";
import NextAuthProvider from "@/provider/NextAuthProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const poppins = Poppins({
  weight: ["200", "400", "500", "600", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Baby Care",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  return (
    <NextAuthProvider session={session}>
        <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.className} ${geistMono.variable} antialiased`}
      >
        <Toaster
  position="top-center"
  reverseOrder={false}
/>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <header><Navbar session={session}></Navbar></header>
          
  
          <div className="">{children}</div>
          <Footer></Footer>
        </ThemeProvider>
      </body>
    </html>

    </NextAuthProvider>
  
  );
}
