import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";

import { getServerSession } from "next-auth";
import NextAuthProvider from "@/provider/NextAuthProvider";
import ThemeProviderWrapper from "@/provider/ThemeProviderWrapper";
import ToasterProvider from "@/provider/ToasterProvider";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";
import { authOptions } from "@/lib/authOptions";

const poppins = Poppins({
  weight: ["200", "400", "500", "600", "700"],
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Baby Care",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body
        className={`${poppins.className} ${geistMono.variable} antialiased`}
      >
        <NextAuthProvider session={session}>
          <ThemeProviderWrapper>
            <ToasterProvider />
            <main>{children}</main>
          </ThemeProviderWrapper>
        </NextAuthProvider>
      </body>
    </html>
  );
}
